version: '3'

services:
  revil.dev_mongodb:
    container_name: revil.dev_mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.container-volumes/mongodb/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: revil.dev

  revil.dev_mongo-express:
    container_name: revil.dev_mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@revil.dev_mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234

  revil.dev_redis:
    container_name: revil.dev_redis
    image: redis
    restart: always
    ports:
      - 6800:6379
    volumes:
      - ./.container-volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf