// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeApp() (App, error) {
	config, err := NewConfig()
	if err != nil {
		return App{}, err
	}
	server := NewServer(config)
	app := NewApp(config, server)
	return app, nil
}
