root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["-mod", "vendor"]
  bin = "./tmp/main"
  cmd = "go build -mod vendor -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "DOBBY_SERVICE_ENV=local ./tmp/main"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = 0
  log = "build-errors.log"
  rerun = false
  rerun_delay = 1000
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
