// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: libs/services/article/article_page.proto

package article

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PageId) Reset() {
	*x = PageId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libs_services_article_article_page_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageId) ProtoMessage() {}

func (x *PageId) ProtoReflect() protoreflect.Message {
	mi := &file_libs_services_article_article_page_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageId.ProtoReflect.Descriptor instead.
func (*PageId) Descriptor() ([]byte, []int) {
	return file_libs_services_article_article_page_proto_rawDescGZIP(), []int{0}
}

func (x *PageId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AddPageParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId string  `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	PrevPageId *string `protobuf:"bytes,2,opt,name=prev_page_id,json=prevPageId,proto3,oneof" json:"prev_page_id,omitempty"`
	NextPageId *string `protobuf:"bytes,3,opt,name=next_page_id,json=nextPageId,proto3,oneof" json:"next_page_id,omitempty"`
}

func (x *AddPageParam) Reset() {
	*x = AddPageParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libs_services_article_article_page_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPageParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPageParam) ProtoMessage() {}

func (x *AddPageParam) ProtoReflect() protoreflect.Message {
	mi := &file_libs_services_article_article_page_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPageParam.ProtoReflect.Descriptor instead.
func (*AddPageParam) Descriptor() ([]byte, []int) {
	return file_libs_services_article_article_page_proto_rawDescGZIP(), []int{1}
}

func (x *AddPageParam) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *AddPageParam) GetPrevPageId() string {
	if x != nil && x.PrevPageId != nil {
		return *x.PrevPageId
	}
	return ""
}

func (x *AddPageParam) GetNextPageId() string {
	if x != nil && x.NextPageId != nil {
		return *x.NextPageId
	}
	return ""
}

var File_libs_services_article_article_page_proto protoreflect.FileDescriptor

var file_libs_services_article_article_page_proto_rawDesc = []byte{
	0x0a, 0x28, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x1e, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x9f, 0x01, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x25, 0x0a, 0x0c, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x76,
	0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0c, 0x6e, 0x65, 0x78,
	0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69,
	0x64, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x32, 0x7e, 0x0a, 0x12, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x50, 0x61, 0x67,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x15, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x41, 0x64,
	0x64, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x0f, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0a, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x67, 0x65, 0x12, 0x0f, 0x2e, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x42, 0x29, 0x5a, 0x27, 0x72, 0x65, 0x76, 0x69, 0x6c, 0x2e, 0x64, 0x65, 0x76, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_libs_services_article_article_page_proto_rawDescOnce sync.Once
	file_libs_services_article_article_page_proto_rawDescData = file_libs_services_article_article_page_proto_rawDesc
)

func file_libs_services_article_article_page_proto_rawDescGZIP() []byte {
	file_libs_services_article_article_page_proto_rawDescOnce.Do(func() {
		file_libs_services_article_article_page_proto_rawDescData = protoimpl.X.CompressGZIP(file_libs_services_article_article_page_proto_rawDescData)
	})
	return file_libs_services_article_article_page_proto_rawDescData
}

var file_libs_services_article_article_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_libs_services_article_article_page_proto_goTypes = []interface{}{
	(*PageId)(nil),       // 0: article.PageId
	(*AddPageParam)(nil), // 1: article.AddPageParam
	(*empty.Empty)(nil),  // 2: google.protobuf.Empty
}
var file_libs_services_article_article_page_proto_depIdxs = []int32{
	1, // 0: article.ArticlePageService.addPage:input_type -> article.AddPageParam
	0, // 1: article.ArticlePageService.deletePage:input_type -> article.PageId
	0, // 2: article.ArticlePageService.addPage:output_type -> article.PageId
	2, // 3: article.ArticlePageService.deletePage:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libs_services_article_article_page_proto_init() }
func file_libs_services_article_article_page_proto_init() {
	if File_libs_services_article_article_page_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_libs_services_article_article_page_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libs_services_article_article_page_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPageParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_libs_services_article_article_page_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_libs_services_article_article_page_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libs_services_article_article_page_proto_goTypes,
		DependencyIndexes: file_libs_services_article_article_page_proto_depIdxs,
		MessageInfos:      file_libs_services_article_article_page_proto_msgTypes,
	}.Build()
	File_libs_services_article_article_page_proto = out.File
	file_libs_services_article_article_page_proto_rawDesc = nil
	file_libs_services_article_article_page_proto_goTypes = nil
	file_libs_services_article_article_page_proto_depIdxs = nil
}
